name: CombatLog
version: '1.0-SNAPSHOT'
main: com.eophantom.combatlog.CombatLog
api-version: 1.19
softdepend: [WorldGuard]
commands:
  combatTime:
    description: check remaining combatTime
    usage: /<command>
    aliases: ct
  blockedCommand:
    description: add blocked command while in combat
    usage: /<command> add/remove/list